### PR TITLE
Add notebook to demo Factsheets integration

### PR DESCRIPTION
**Pull request by harshit-sh**
@arsuryan @kishore-patel Please review. Thanks!

### CODE REVIEW

**Comment by kishore-patel** [comment]
@harshit-sh - File extension is missing so I am not able to view it as notebook.

**Comment by harshit-sh** [comment]
Thanks @kishore-patel. I have updated the file extension.

**Comment by kishore-patel** [comment]
@harshit-sh - Please incorporate the following 2 minor comments.

1. Notebook says use `Default Spark 3.2 & Python 3.9` but it upgrades spark to 3.0.2 level instead of 3.2
2. Generally in all sample notebooks we use `***` as value for the parameter which user needs to fill. You are using "" as value. Can we change that?

**Review by kishore-patel — APPROVED** [review]

**Comment by harshit-sh** [comment]
Thanks @kishore-patel. I have addressed the review comments. Could you please merge the PR as I don't have write access to the repo.

**Comment by prempiyush** [comment]
Merging per @harshit-sh' request.

**Comment by harshit-sh** [comment]
Thanks @prempiyush!

**Pull request merged**
