### PR TITLE
Replaced MRM related API calls in notebooks with corresponding SDK functions

### PR DESCRIPTION
**Pull request by Hari-Krishnan3**
Issue : https://github.ibm.com/aiopenscale/tracker/issues/29076

### CODE REVIEW

**Comment by kishore-patel** [comment]
@Hari-Krishnan3 - Did you ran notebooks against latest SDK code?

**Comment by Hari-Krishnan3** [comment]
> @Hari-Krishnan3 - Did you ran notebooks against latest SDK code?

I validated the mrm function related change by running the depended cells with 3.0.30 version of `ibm-watson-openscale.`  Have not ran the notebooks end to end.

**Comment by kishore-patel** [comment]
@Hari-Krishnan3 - Can we atleast run one E2E MRM notebook? Try running https://github.com/IBM/watson-openscale-samples/blob/main/Cloud%20Pak%20for%20Data/WML/notebooks/model%20risk%20management/MRM%20E2E%20with%20Openpages%20on%20CP4D.ipynb

**Comment by Hari-Krishnan3** [comment]
As discussed over call. Since this change updates software specification to `spark-mllib_3.3` We will deliver this change along with 4.7 release.

**Comment by Hari-Krishnan-Geek** [comment]
Issue 2: https://github.ibm.com/aiopenscale/tracker/issues/31135

**Comment by Hari-Krishnan-Geek** [comment]
@kishore-patel I have updated this PR by modifying the software spec in other notebooks also. Please review.

**Comment by kishore-patel** [comment]
Looks good.  We will not merge this PR until the date of 4.7 release

**Review by kishore-patel — APPROVED** [review]

**Comment by kishore-patel** [comment]
@Hari-Krishnan3 - Can we go ahead and merge this PR?

**Pull request merged**
