### PR TITLE
Added quality monitoring for image based models

### PR DESCRIPTION
**Pull request by Hari-Krishnan3**
aiopenscale/tracker#22038

### CODE REVIEW

**Comment by ravichamarthy** [comment]
Can you please share the modified notebook here @Hari-Krishnan3 ?
So that I can run it in the CPD 4.6 cluster and validate the same.
Thanks.

**Comment by Hari-Krishnan3** [comment]
> Can you please share the modified notebook here @Hari-Krishnan3 ? So that I can run it in the CPD 4.6 cluster and validate the same. Thanks.

Sure. Please find the attached notebooks
[image_notebooks.zip](https://github.com/IBM/watson-openscale-samples/files/10380393/image_notebooks.zip)

**Comment by ravichamarthy** [comment]
The binary related notebook is failing with this error:

```
<class 'Exception'> name 'project' is not defined
```

**Comment by Hari-Krishnan3** [comment]
I have updated the PR. Please review.. @ravichamarthy @sokollip

**Review by ravichamarthy — APPROVED** [review]
Looks good to me ..

**Comment by kishore-patel** [comment]
@Hari-Krishnan3 - We need to test it with Python 3.10 and update the notebook to reflect that.

**Comment by Hari-Krishnan3** [comment]
> @Hari-Krishnan3 - We need to test it with Python 3.10 and update the notebook to reflect that.

Sure. I will test it and update. Thanks

**Comment by Hari-Krishnan3** [comment]
> @Hari-Krishnan3 - We need to test it with Python 3.10 and update the notebook to reflect that.

I have verified it with python 3.10 and updated the notebook. Please review ..

**Comment by ravichamarthy** [comment]
Hi @Hari-Krishnan3 Can you please go ahead and fix this PR?

**Pull request merged**
