### PR TITLE
cloud notebooks - update metrics-plugin version, add input_data_type into definitions

### PR DESCRIPTION
**Pull request by nelwinn**
- Updated metrics-plugin version for cloud notebooks to pick up ibm-metrics-plugin[notebook]~=3.0.0
- Added input_data_type to definitions

### CODE REVIEW

**Review by prempiyush — APPROVED** [review]

**Comment by pgoyal-ibm** [comment]
@nelwinn Was this change merged in the internal repo?
If not, please merge it there first and then raise a PR for the public repo. The steps were shared on how the changes need to flow for notebooks please follow the same.

cc: @arsuryan

**Comment by nelwinn** [comment]
@pgoyal-ibm Yes, the changes were already merged in internal repo

**Comment by pgoyal-ibm** [comment]
@nelwinn I don't see a PR for the same, can you please refer that here?

**Comment by pgoyal-ibm** [comment]
@nelwinn ^^

**Pull request merged**
