### PR TITLE
updating image_uri to new requirements for accessing aws

### PR DESCRIPTION
**Pull request by csgorham**
[https://sagemaker.readthedocs.io/en/stable/v2.html](url)

Image URI Functions (e.g. get_image_uri)
The following functions have been deprecated in favor of [sagemaker.image_uris.retrieve()](https://sagemaker.readthedocs.io/en/stable/api/utility/image_uris.html#sagemaker.image_uris.retrieve):

sagemaker.amazon_estimator.get_image_uri()

sagemaker.fw_utils.create_image_uri()

sagemaker.fw_registry.registry()

sagemaker.utils.get_ecr_image_uri_prefix()

### CODE REVIEW

**Comment by kishore-patel** [comment]
@csgorham - Please resolve the merge conflicts

**Comment by csgorham** [comment]
@kishore done!

**Review by kishore-patel — APPROVED** [review]

**Comment by kishore-patel** [comment]
@csgorham - Do you want me to merge it?

**Comment by csgorham** [comment]
Yes please :)

**Comment by kishore-patel** [comment]
Done

**Pull request merged**
