### PR TITLE
Uploaded batch parity notebooks for 4.6

### PR DESCRIPTION
**Pull request by Hari-Krishnan3**
aiopenscale/tracker#28468

### CODE REVIEW

**Comment by harivkum** [comment]
@Hari-Krishnan3 Please refer to folder `4.5` and `4.0` for the pattern to follow.
Also, the files are to be renamed in accordance with what we have in other folders. 

Please check and update this PR. Thanks.

**Comment by Hari-Krishnan3** [comment]
> @Hari-Krishnan3 Please refer to folder `4.5` and `4.0` for the pattern to follow. Also, the files are to be renamed in accordance with what we have in other folders.
> 
> Please check and update this PR. Thanks.

I have made these changes. Please verify ..

**Review by kishore-patel — APPROVED** [review]

**Comment by kishore-patel** [comment]
@Hari-Krishnan3 - Don't merge these notebooks yet since we have not release 4.6

**Comment by kishore-patel** [comment]
@arsuryan - When do we want to merge this PR for 4.6 ?

**Comment by harivkum** [comment]
@Hari-Krishnan3 `samples` folder now contains only one file. Please make sure to add previous notebooks as well. Thanks.

**Comment by Hari-Krishnan3** [comment]
@kishore-patel @harivkum This PR is updated with all the notebooks now. Please verify.

**Comment by kishore-patel** [comment]
We need to merge this PR on the day of CP4D 4.6 release

cc: @arsuryan

**Comment by kishore-patel** [comment]
@Hari-Krishnan3 - Are we saying that these notebooks should be executed using either Python 3.9 or 3.10?

**Comment by Hari-Krishnan3** [comment]
> @Hari-Krishnan3 - Are we saying that these notebooks should be executed using either Python 3.9 or 3.10?

These 4 notebooks are specifying the python versions:

Watson OpenScale - Monitor models with data in Hive.ipynb
Watson OpenScale - Monitor models with data in DB2.ipynb
Watson OpenScale -  Onboard models for monitoring using training data table and a sample csv.ipynb (for data in hive and DB2 )

**Pull request merged**
