### PR TITLE
Removed asking training_data_schema while creating subscription

### PR DESCRIPTION
**Pull request by Hari-Krishnan3**
aiopenscale/tracker#28515

### CODE REVIEW

**Comment by kishore-patel** [comment]
@Hari-Krishnan3 - Did you run both the notebooks successfully?

**Comment by sokollip** [comment]
Hi @Hari-Krishnan3  , A general comment which needs to be added in both the notebooks . We need to inform user that they can supply training_data_schema but it is not mandatory .So add a cell or markdown text saying how they can supply this .

**Comment by Hari-Krishnan3** [comment]
While running https://github.com/IBM/watson-openscale-samples/blob/main/IBM%20Cloud/WML/notebooks/binary/spark/Watson%20OpenScale%20and%20Watson%20ML%20Engine.ipynb e2e and subscription is getting created without training_data_schema, But there are other issues like

1) Storing custom metrics cannot be done with the hardcoded run_id. I removed the run_id and then it is working.
2) There is no parameter passed while creating monitor_instance, This is fixed by passing an empty parameter.

I will include these changes also in the PR. Thanks

**Comment by kishore-patel** [comment]
> I will include these changes also in the PR. Thanks

Ok

**Comment by Hari-Krishnan3** [comment]
I have updated the PR. Please review @kishore-patel @sokollip

**Review by sokollip — APPROVED** [review]
Thank you for making this change . lgtm. Probably we can add a note that schemas will get added/updated after first PL request .

**Review by kishore-patel — APPROVED** [review]

**Pull request merged**
